import "~/styles/globals.css";

import { Inter } from "next/font/google";

import Navbar from "./_components/navbar/navbar";
import { AppProvider } from "./providers";

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-sans",
});

export const metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default async function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <AppProvider>
        <body className={`bg-stone-800 font-sans ${inter.variable}`}>
          <Navbar />
          <div className={`pl-[calc(100vw-100%)]`}>{children}</div>
        </body>
      </AppProvider>
    </html>
  );
}
